pub mod agents;
pub mod bridge;
pub mod bridge_auth;
pub mod bridge_state;
pub mod config;
pub mod daemon;
pub mod error;
pub mod mcp;
pub mod mcp_server;
pub mod mcp_tools;
pub mod platform;
pub mod policy;
mod praefectus_adapter;
pub use error::{Error, Result};
