name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build bridge
        run: bun run build:bridge

      - name: Build project
        run: zig build -Doptimize=ReleaseSafe

      - name: Run tests
        run: zig build test
